<script type="text/javascript">
    //<![CDATA[
    function checkApply() {
        new Ajax.Request('<?php echo $this->getAjaxCheckUrl() ?>', {
            method:     'get',
            onSuccess: function(transport){

                if (transport.responseText){
                    alert('Design Applied');
                }
            }
        });
    }
    //]]>
</script>

<div class="pp-buttons-container">
    <button id="<?php echo $block->getId() ?>" onclick="checkApply(); return false;">
        <span><?php echo $block->escapeHtml($block->getButtonLabel()); ?></span>
    </button>
</div>