<div class="message">
  <div class="content">
    <h2>Helpful Links</h2>
    <p><a href="https://github.com/PMET-public/module-themecustomizer#readme" target="_blank">Documentation</a></p>
    <p><a href="<?php  echo $this->getUrl('theme/design_config/index');?>" target="_blank">Upload A Logo</a></p>
    <p><a href="https://coolors.co/browser/latest/1" target="_blank">Color Inspiration</a></p>
  </div>
</div>
